services:
  # webアプリケーションのコンテナ
  app:
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
      target: php83 # php82 php81 php80 php74 php73(app/Dockerfileの指定のバージョンのコメントアウトを解除)
    volumes:
      - ./src:/var/www
    working_dir: /var/www

  # webサーバーのコンテナ
  web:
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./src:/var/www

  # dbサーバーのコンテナ
  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - asai-db-mysql-volume:/var/lib/mysql

volumes:
  asai-db-mysql-volume:
